name: build
on: push
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Lint (Linux only)
        if: runner.os == 'Linux'
        run: |
          cargo clippy --verbose -- -D warnings # elevates warnings to errors
      - name: Build
        run: |
          cargo build --verbose # debug build